## Description : 
This document will be all about practicing ML Models

In [107]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
import time
import plotly.express as pe
import plotly.offline as pyo
import plotly.graph_objects as go

from datetime import datetime
#
os.chdir('../')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [108]:
from lib import dataprocess as dp
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [109]:
dp.process_downloaded_data('Madison','wunderground','pws','2021')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gaurav/UAH/data/Madison/pws_data_madison/2021'

In [4]:
df = pd.read_csv('data/Madison_2021/master_Madison_pws_.csv')
df = dp.process_wunder(df)

In [103]:
stations = df.station.unique()
station_1 = df[df.station == stations[0]]

station_1['hour'] = station_1['beg_time'].apply(lambda x : x.hour)
station_1['month'] = station_1['beg_time'].apply(lambda x : x.month)
temp_mean = station_1.groupby(['hour','month']).mean()

# pe.line(temp_mean['temperature'])
# temp_mean.index[-1][0]
for i in range(3):
    pe.line(temp_mean.loc[i]['temperature'])

/var/folders/qr/fds_zg7j76g51mq0zmqdqfnc0000gn/T/ipykernel_16591/2337133973.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/qr/fds_zg7j76g51mq0zmqdqfnc0000gn/T/ipykernel_16591/2337133973.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

NameError: name 'plt' is not defined

In [7]:
df.groupby('station')

In [8]:
from math import radians, cos, sin, asin, sqrt, degrees, atan2

x = df.groupby(['latitude','longitude']).size().reset_index()

def distance_haversine(p1, p2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    Haversine
    formula: 
        a = sin²(Δφ/2) + cos φ1 ⋅ cos φ2 ⋅ sin²(Δλ/2)
                        _   ____
        c = 2 ⋅ atan2( √a, √(1−a) )
        d = R ⋅ c

    where   φ is latitude, λ is longitude, R is earth’s radius (mean radius = 6,371km);
            note that angles need to be in radians to pass to trig functions!
    """
    lat1, lon1 = p1
    lat2, lon2 = p2

    R = 6371 # km - earths's radius

    # convert decimal degrees to radians 
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])

    # haversine formula 
    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) # 2 * atan2(sqrt(a), sqrt(1-a))
    d = R * c
    return d

In [10]:
distance_haversine(x.iloc[0].values[:2],x.iloc[4].values[:2])

8.845493292884914

In [21]:
con_df = df[df.station=='KWICOTTA13']
con_df.loc[:,'predicted'] = 0.0
# con_df.loc[:, 'predicted'] = 0.0
con_df

/var/folders/qr/fds_zg7j76g51mq0zmqdqfnc0000gn/T/ipykernel_90019/2953242346.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,station,beg_time,Unnamed: 0,epoch,latitude,longitude,humidityAvg,temperature,windspeed,dewpt,heatindex,precipRate,day_of_year,predicted
0,KWICOTTA13,2021-01-01 00:00:00,0.0,1.609484e+09,43.057156,-89.244202,90.0,-9.0,6.0,-10.0,-9.0,0.0,1,0.0
1,KWICOTTA13,2021-01-01 01:00:00,1.0,1.609488e+09,43.057156,-89.244202,90.0,-8.0,2.0,-10.0,-8.0,0.0,1,0.0
2,KWICOTTA13,2021-01-01 02:00:00,2.0,1.609492e+09,43.057156,-89.244202,90.0,-8.0,1.0,-10.0,-8.0,0.0,1,0.0
3,KWICOTTA13,2021-01-01 03:00:00,3.0,1.609495e+09,43.057156,-89.244202,90.0,-9.0,2.0,-10.0,-8.0,0.0,1,0.0
4,KWICOTTA13,2021-01-01 04:00:00,4.0,1.609499e+09,43.057156,-89.244202,90.0,-9.0,2.0,-10.0,-9.0,0.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4716,KWICOTTA13,2021-12-30 19:00:00,4717.0,1.640916e+09,43.057156,-89.244202,92.0,-2.0,4.0,-3.0,-2.0,0.0,364,0.0
4717,KWICOTTA13,2021-12-30 20:00:00,4718.0,1.640920e+09,43.057156,-89.244202,93.0,-2.0,7.0,-3.0,-2.0,0.0,364,0.0
4718,KWICOTTA13,2021-12-30 21:00:00,4719.0,1.640923e+09,43.057156,-89.244202,93.0,-2.0,5.0,-3.0,-2.0,0.0,364,0.0
4719,KWICOTTA13,2021-12-30 22:00:00,4720.0,1.640927e+09,43.057156,-89.244202,93.0,-2.0,6.0,-3.0,-2.0,0.0,364,0.0
4720,KWICOTTA13,2021-12-30 23:00:00,4721.0,1.640930e+09,43.057156,-89.244202,93.0,-2.0,5.0,-3.0,-2.0,0.0,364,0.0

In [10]:
# # for _,group in grouped_data:
# #     coordinates = group[['latitude', 'longitude']].values
# #     nn_model = NearestNeighbors(n_neighbors=4)
# #     nn_model.fit(coordinates)
# #     distances, indices = nn_model.kneighbors(coordinates, n_neighbors=4)
# #     nearest_indices = indices[:, 1:]  
    
# #     for i, row in group.iterrows():
# #         current_lat, current_lon = row['latitude'], row['longitude']
# # #         print(i)
# #         group.iloc[nearest_indices[i]]['temperature']
# #         predicted_temperature = nearest_temperatures.mean()
        
# #         df.at[i, 'predicted_temperature'] = predicted_temperature

# temp_data = grouped_data.head(25)
# coords = temp_data[['latitude','longitude']].values
# nn_model = NearestNeighbors(n_neighbors=4)
# nn_model.fit(coords)

# distances, indices = nn_model.kneighbors(coordinates, n_neighbors=4)

# grouped_data.get_group('KWICOTTA13')[['latitude', 'longitude']]

for group in grouped_data:
    print(group[0])

KWICOTTA13
KWIFITCH21
KWIFITCH30
KWIFITCH35
KWIFITCH38
KWIFITCH40
KWIFITCH41
KWIFITCH42
KWIFITCH46
KWIFITCH6
KWIFITCH8
KWIMADIS1
KWIMADIS104
KWIMADIS114
KWIMADIS118
KWIMADIS119
KWIMADIS120
KWIMADIS130
KWIMADIS132
KWIMADIS134
KWIMADIS138
KWIMADIS151
KWIMADIS162
KWIMADIS175
KWIMADIS18
KWIMADIS187
KWIMADIS194
KWIMADIS195
KWIMADIS196
KWIMADIS198
KWIMADIS199
KWIMADIS201
KWIMADIS205
KWIMADIS208
KWIMADIS212
KWIMADIS214
KWIMADIS215
KWIMADIS222
KWIMADIS223
KWIMADIS226
KWIMADIS233
KWIMADIS237
KWIMADIS238
KWIMADIS239
KWIMADIS242
KWIMADIS249
KWIMADIS259
KWIMADIS262
KWIMADIS266
KWIMADIS270
KWIMADIS273
KWIMADIS278
KWIMADIS279
KWIMADIS283
KWIMADIS284
KWIMADIS287
KWIMADIS288
KWIMADIS290
KWIMADIS292
KWIMADIS293
KWIMADIS294
KWIMADIS295
KWIMADIS298
KWIMADIS301
KWIMADIS306
KWIMADIS308
KWIMADIS309
KWIMADIS310
KWIMADIS311
KWIMADIS312
KWIMADIS313
KWIMADIS314
KWIMADIS324
KWIMADIS328
KWIMADIS33
KWIMADIS331
KWIMADIS332
KWIMADIS333
KWIMADIS334
KWIMADIS335
KWIMADIS336
KWIMADIS338
KWIMADIS340
KWIMADIS342
KWIMADIS343
KWIMADIS344
KWIMADIS345
KWIMADIS346
KWIMADIS347
KWIMADIS349
KWIMADIS35
KWIMADIS350
KWIMADIS352
KWIMADIS353
KWIMADIS354
KWIMADIS357
KWIMADIS359
KWIMADIS361
KWIMADIS362
KWIMADIS363
KWIMADIS364
KWIMADIS365
KWIMADIS366
KWIMADIS367
KWIMADIS369
KWIMADIS370
KWIMADIS371
KWIMADIS372
KWIMADIS377
KWIMADIS378
KWIMADIS41
KWIMADIS47
KWIMADIS48
KWIMADIS50
KWIMADIS52
KWIMADIS65
KWIMADIS87
KWIMCFAR10
KWIMCFAR19
KWIMCFAR20
KWIMCFAR22
KWIMCFAR8
KWIMCFAR9
KWIMIDDL11
KWIMIDDL12
KWIMIDDL14
KWIMIDDL19
KWIMIDDL23
KWIMIDDL25
KWIMIDDL36
KWIMIDDL39
KWIMIDDL41
KWIMIDDL45
KWIMIDDL46
KWIMIDDL58
KWIMIDDL59
KWIMIDDL62
KWIMONON10
KWIMONON4
KWIMONON7
KWIMONON8
KWISUNPR14
KWISUNPR29
KWISUNPR42
KWISUNPR63
KWISUNPR7
KWISUNPR84
KWIVERON21
KWIVERON28
KWIVERON43
KWIVERON46
KWIVERON48
KWIVERON50
KWIVERON57
KWIVERON58
KWIVERON71
KWIVERON72
KWIWAUNA18
KWIWAUNA25
KWIWAUNA31
KWIWAUNA32
KWIWAUNA34
KWIWAUNA38
KWIWAUNA4
KWIWAUNA40
KWIWAUNA41
KWIWAUNA42
KWIWAUNA43
KWIWAUNA46
KWIWINDS10

In [7]:
df.head()

,station,beg_time,Unnamed: 0,epoch,latitude,longitude,humidityAvg,temperature,windspeed,dewpt,heatindex,precipRate,day_of_year,predicted_temperature
0,KWICOTTA13,2021-01-01 00:00:00,0.0,1.609484e+09,43.057156,-89.244202,90.0,-9.0,6.0,-10.0,-9.0,0.0,1,0.0
1,KWICOTTA13,2021-01-01 01:00:00,1.0,1.609488e+09,43.057156,-89.244202,90.0,-8.0,2.0,-10.0,-8.0,0.0,1,0.0
2,KWICOTTA13,2021-01-01 02:00:00,2.0,1.609492e+09,43.057156,-89.244202,90.0,-8.0,1.0,-10.0,-8.0,0.0,1,0.0
3,KWICOTTA13,2021-01-01 03:00:00,3.0,1.609495e+09,43.057156,-89.244202,90.0,-9.0,2.0,-10.0,-8.0,0.0,1,0.0
4,KWICOTTA13,2021-01-01 04:00:00,4.0,1.609499e+09,43.057156,-89.244202,90.0,-9.0,2.0,-10.0,-9.0,0.0,1,0.0

In [ ]:
concerned_df = df[df.station =='KWICOTTA13']
pe.line(concerned_df,x = 'beg_time',y= ['temperature','predicted_temperature'])

In [8]:
grouped_data = df.groupby(['latitude','longitude'])

In [10]:
grouped_data.values

AttributeError: 'DataFrameGroupBy' object has no attribute 'values'